name: Build process for Debug APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checks the repository onto the runner
        uses: actions/checkout@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Run tests
        run: ./gradlew test

      - name: Build Debug_Apk
        run: ./gradlew clean assembleDebug

      - name: Upload Debug_APK
        uses: actions/upload-artifact@v2
        with:
          name: debug_apk
          path: app/build/outputs/apk/debug/app-debug.apk