name: Build process for Debug APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checks the repository onto the runner
      - uses: actions/checkout@v2
      
    
    


