name: Build process for Debug APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checks the repository onto the runner
        uses: actions/checkout@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Run tests
        run: ./gradlew test

      - name: debug apk
        run: ./gradlew clean assembleDebug
      
      - name: Release Debug-APK
        uses: actions/upload-artifact@v2
        with:
          tag_name: version
          asset_path: app/build/outputs/apk/debug/app-debug.apk
          asset_name: our_name.apk
          asset_content_type: WG-Zusammenleben/zip
