name: Build process for Debug APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
# test
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checks the repository onto the runner
        uses: actions/checkout@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      # Testing
      - name: Run Unit tests
        run: ./gradlew test

      - name: By Findings Report
        uses: actions/upload-artifact@v2
        with:
          name: Unit Test-Reports
          path: app/build/reports
        if: always()

      #Building and Upload
      - name: Build Debug_Apk
        run: ./gradlew assembleDebug

      - name: Upload Debug_APK
        uses: actions/upload-artifact@v2
        with:
          name: debug_apk
          path: app/build/outputs/apk/debug/app-debug.apk

      # Create Release
      
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release Version
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
