name: Testing

on:
  push:
    branches:
      - main
      - development
      - interfacedesign
  pull_request:
    branches:
      - main
      - development
      - interfacedesign

jobs:
  Run-Unit-Test:
    runs-on: ubuntu-latest

    steps:
      - name: checks the repository onto the runner
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Run Unit test
        run: ./gradlew test

      - name: By Findings Report
        uses: actions/upload-artifact@v2
        with:
          name: Unit-Test-Report
          path: app/build/reports
        if: always()
  
  Super-Linter:
    runs-on: ubuntu-latest

    steps:
      - name: checks the repository onto the runner
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
      
      - name: Super-Linter
        uses: github/super-linter@v4.8.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true
          
  Run_Checkstyle:
    runs-on: ubuntu-latest
    
    steps:
      - name: checks the repository onto the runner
        uses: actions/checkout@v2
        
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
    
      - name: Run check style
        uses: nikitasavinov/checkstyle-action@0.4.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
