 name: "Issue Actions"
    on: ["push"]
    jobs:
      build:
        runs-on: "ubuntu-latest"
        steps:
          - uses: "actions/checkout@master"
          - name: "Add a TODO-Comment to Issue"
            uses: "alstr/todo-to-issue-action@v4.5"
            id: "todo"
